---
# Defines deployment design and assigns role to server groups

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  sudo: True
  roles:
  - ceph-common

- hosts: mons
  sudo: True
  roles:
  - ceph-mon

- hosts: osds
  sudo: True
  roles:
  - ceph-osd

- hosts: mdss
  sudo: True
  roles:
  - ceph-mds

- hosts: rgws
  sudo: True
  roles:
  - ceph-radosgw

- hosts: clients
  sudo: True
  roles:
  - ceph-common
  - ceph-client
